### ISSUE TITLE
Self Pings

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#53] opened 2015-10-02 02:25 UTC
The code used to stop self pings only stops webmentions to the same URL, not to the same site.

Suggesting it should check if the URL includes site_url to avoid this.

**Comment by pfefferle** [comment] 2015-10-02 05:29
I am not sure if we should disable self pings by default, because they might be useful/wanted for some users.

**Comment by dshanske** [comment] 2015-10-02 05:36
Then I would ask the question regarding the presentation of self-pings, at the least, and a simple way to disable them if someone chooses in the code.

For example, what if we identify them and provide an alternate syntax. For example, "This article was mentioned elsewhere on 'this site'.

**Comment by dshanske** [comment] 2015-10-02 05:39
Is there any scenario where someone would do something other than mention on their own site, I wonder?

**Comment by pfefferle** [comment] 2015-10-02 05:40
ok, I think we could add the setting here and an alternate type for self pings to the semantic-linkbacks plugin!

very good points! :thumbsup:

**Comment by pfefferle** [comment] 2015-10-02 05:41
perhaps rsvp ;)

**Comment by armingrewe** [comment] 2015-10-02 07:50
I fairly regularly use self pings, mainly for entries which somehow belong together, e.g. pictures in a series. Hence I'd like to keep the functionality, but would be fine with different wording.

**Comment by singpolyma** [comment] 2015-10-15 20:02
Is this not a duplicate of #32 ?

**Comment by dshanske** [comment] 2015-10-16 00:00
It is the question of self ping presentation

**Closed** 2015-10-23 18:57 UTC
